### Test Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "id": "testuserid",
    "username": "notsuperuser",
    "email": "test@email.com",
    "bio": "why, thank you",
    "pfp": "src/assets/def-pfp.png"
}

### Test Get User By ID
GET http://localhost:8080/api/users/fakeid

### Test Get All Users
GET http://localhost:8080/api/users

### Test Delete User
DELETE http://localhost:8080/api/users/testuserid

### Test Create Thread
POST http://localhost:8080/api/threads/
Content-Type: application/json

{
    "id": "sd7630ckkoskocrandomlol",
    "title": "Test Thread",
    "content": "",
    "authorId": "sd7875sssdsdssrandomlol",
    "authorName": "testusername",
    "pfpUrl": "",
    "category": "books",
    "postCount": 0
}

### Test Get all Posts in a Thread By ID
GET http://localhost:8080/api/threads/EJVOqyxbikURoUI5nI70/posts

### Test Add a post to a thread
POST http://localhost:8080/api/threads/EJVOqyxbikURoUI5nI70/posts
Content-Type: application/json

{
    "id": "",
    "content": "some more more content ig",
    "authorId": "sd7875sssdsdssrandomlol",
    "authorName": "testusername",
    "pfpUrl": ""
}